detectors:
  IrresponsibleModule:
    enabled: false
  TooManyInstanceVariables:
    max_instance_variables: 8

exclude_paths:
  - db/
  - node_modules/

directories:
  "app/controllers": # using variable initialization in before_action
    InstanceVariableAssumption:
      enabled: false
