default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= ENV["POSTGRES_USER"] || Rails.application.credentials.postgresql[:user] %>
  password: <%= ENV["POSTGRES_PASSWORD"] || Rails.application.credentials.postgresql[:password] %>

development:
  <<: *default
  database: electric_curcuit_testing_platform_development

test:
  <<: *default
  database: electric_curcuit_testing_platform_test

production:
  <<: *default
  database: electric_curcuit_testing_platform_production
  username: electric_curcuit_testing_platform
  password: <%= ENV['ELECTRIC_CURCUIT_TESTING_PLATFORM_DATABASE_PASSWORD'] %>
